@Library('blackduck-logs-publisher') _

pipeline {
    agent { label 'mac-sh' }

    stages {
        stage("Build") {
            steps {
                script {
                    echo "JOB_NAME: ${env.JOB_NAME}"

                    dir('nodejs-npm') {
                        sh 'node --version'
                        sh 'npm --version'
                        sh 'npm install'
                    }
                }
            }
        }

        stage("polaris-source-upload") {
            steps {
                script {
                    dir('nodejs-npm') {
                        security_scan polaris_assessment_types: 'SAST,SCA', polaris_test_sast_location: 'remote', polaris_test_sca_location: 'remote',
                        polaris_waitForScan: true, product: 'polaris'
                          

                        
                    }
                }
            }
        }
    }

    post {
        always {
            pushJenkinsLogsToGitHub([
                githubOrg: 'polaris-jenkins-samples',
                repoName: 'source-upload',
                retentionCount: 5
            ])
        }
    }
}
